export const ELEMENTS = {
   
    MenuProfile: '.header__login > :nth-child(1)',
    MenuProfilesair: '.header__profile',
    ButtonEntrarProfile: '.menu-drawer__signin',
    ButtonSairProfile: '.menu-drawer__signout > span',
    ButtonCriarContaProfile: '',
    LinkSobre: '',
    RadioRegistro: '',
    RadioEmail: '#sf-is-not-hcp',
    SelectTipoHCP: '#hcp-type',
    SelectEstado: '#uf',
    InputNumeroRegistro: '#lf-registro',
    LinkEsqueceuSenha: '',
    ButtonEntrar: '#sf-continue-validation',
    LinkCadastrese: '',
    InputSenha: '#sf-password',
    InputEmail: '#lf-email',
    ValidaLogin: '.c-text--bold > :nth-child(2)',
    ValidaLogout: '.c-navbar__item > p',
    UFError: '#uf-error',
    RegistroError: '#registro-error',
    PassError: '#pass-error',
    GenericError: '#generic-error',
    ButtonFecharModalLogin: '.c-base-modal-content__head > .icon'
}
