export const ELEMENTS = {
   
    MenuProfile: '.menu-profile__indicator',
    ButtonEntrarProfile: '.menu-profile > #menu-profile-panel > .menu-profile__panel-content > .menu-profile__panel-row > #btnLogin',
    ButtonSairProfile: '.menu-profile > #menu-profile-panel > .menu-profile__panel-content > .menu-profile__panel-row > .menu-profile__panel-item--danger',
    ButtonCriarContaProfile: '',
    LinkSobre: '',
    RadioRegistro: '',
    RadioEmail: '#sf-is-not-hcp',
    SelectTipoHCP: '#hcp-type',
    SelectEstado: '#uf',
    InputNumeroRegistro: '#lf-registro',
    LinkEsqueceuSenha: '',
    ButtonEntrar: '#sf-continue-validation',
    LinkCadastrese: '',
    InputSenha: '#sf-password',
    InputEmail: '#lf-email',
    ValidaLogin: '.c-text--bold > :nth-child(2)',
    ValidaLogout: '.c-navbar__item > p',
    UFError: '#uf-error',
    RegistroError: '#registro-error',
    PassError: '#pass-error',
    GenericError: '#generic-error',
}
