export const ELEMENTS = {
   
    MenuProfile: '.menu-profile__indicator',
    ButtonEntrarProfile: '.menu-profile > #menu-profile-panel > .menu-profile__panel-content > .menu-profile__panel-row > #btnLogin',
    ButtonSairProfile: '.menu-profile > #menu-profile-panel > .menu-profile__panel-content > .menu-profile__panel-row > .menu-profile__panel-item--danger',
    ButtonCriarContaProfile: '',
    LinkSobre: '',
    CheckBoxTermos: '#opt-in',
    RadioRegistro: '',
    RadioEmail: '#sf-is-not-hcp',
    SelectTipoHCP: '#hcp-type',
    SelectEstado: '#uf',
    InputNumeroRegistroErro: '#lf-registro',
    LinkEsqueceuSenha: '',
    ButtonEntrar: '#sf-continue-validation',
    LinkCadastrese: '',
    InputSenha: '#sf-password',
    InputEmail: '#sf-email',
    ValidaLogin: '.c-text--bold > :nth-child(2)',
    ValidaLogout: '.c-navbar__item > p',
    UFError: '#uf-error',
    EmailError: '#email-error',
    RegistroJaCadastrado: '.c-text--h3 > strong',
    EmailJaCadastrado: '.c-text--h3 > strong',
    RegistroError: '#registro-error',
    TermsError: '#terms-error',
    PassError: '#pass-error',
    GenericError: '#generic-error',
    ButtonFecharModalLogin: '.c-base-modal-content__head > .icon',
    InputName: '#sf-name',
    InputLastName: '#sf-lastname',
    InputTelefone: '#sf-cellphone',
    InputSenha: '#sf-password',
    InputConfirmaSenha: '#sf-password-confirm',
    ValidaCadastro: '.c-base-modal-content__body > :nth-child(1)',
    ButtonCriarContaProfile: '.menu-profile > #menu-profile-panel > .menu-profile__panel-content > .menu-profile__panel-row > #btnSignUp', 
    InputNumeroRegistro: '#sf-register-2'
}
